### ISSUE TITLE
Speed of TOF is much slower than expected

### ISSUE THREAD

**Issue by AnderBiguri** [NikEfth/STIR#16]
Hi Nikos!

I have been playing with this for a bit (massive work to make TOF available, thanks), and I noticed that when I forward project, generally it takes 5 times more than expected, i.e. 5 times more than N times a single forward projection, where N is number of TOF bins. 

So for 29 bins, it takes 29*5 ~= 140 times more to do a forward projection than when I create a non-TOF sinogram. Tested it with 13 bins too, same ratio. All for the GE DMI 3-ring.

Is this something that you know about?   If so, do you know _why_ it happens? Do you have any pointers about which part of the TOF code may be the one that causes this? 

I am on track of launching a very large chunk of simulations, and would like to try to do them with TOF, but that x5 does really take my simulation length into month mark, so I would be very interested into accelerating it as much as possible. 

---- 

code to replicate, via SIRF. Use #15 parameter file as 'DMI_template_tof_mashed.hs'

```
import sirf.STIR as stir
import numpy as np
import time

def set_up_pet_model(acq_data_template,attn_image,image_template):
    # Create sensitivity model based on the acquisition model and attenuation image
    asm_attn = stir.AcquisitionSensitivityModel(attn_image, stir.AcquisitionModelUsingRayTracingMatrix())
    
    # now forward project a white image with the sensitivity model, and store them back in a new sensitivity model (to save computational time)
    if acq_data_template.shape[0]>1 and len(acq_data_template.shape)==4: # if TOF
        print("is tof!")
        
        acq_data_ct=stir.AcquisitionData('Discovery MI') #TODO change to the current template.
        asm_attn.set_up(acq_data_ct)
        asm_attn = stir.AcquisitionSensitivityModel(asm_attn.forward(acq_data_ct.get_uniform_copy(1)))
    else:
        asm_attn.set_up(acq_data_template)
        asm_attn = stir.AcquisitionSensitivityModel(asm_attn.forward(acq_data_template.get_uniform_copy(1)))

    # reuse this code to set up pet model (note we are just using template info here, not data)
    acq_model = stir.AcquisitionModelUsingRayTracingMatrix()
    acq_model.set_acquisition_sensitivity(asm_attn)
    acq_model.set_up(acq_data_template,image_template)
    return acq_model





ad_ntof=stir.AcquisitionData('Discovery MI')
ad_tof=stir.AcquisitionData('DMI_template_tof_mashed.hs')

#just trust me these are the images. 
pet_phantom=stir.ImageData('/home/anderbiguri/Documents/MATLAB/GE/DWB-PET-WIP/Dyamic_PET_simulation/output/P010/systematic_motion/pre-recon/dynamicXcat_WB_pre-recon_12.hv')
ct_phantom =stir.ImageData('/home/anderbiguri/Documents/MATLAB/GE/DWB-PET-WIP/Dyamic_PET_simulation/output/P010/systematic_motion/pre-recon/dynamicXcat_WB_pre-recon_CT.hv')

pet_arr=pet_phantom.as_array()
ct_arr=ct_phantom.as_array()



#%% Set up acm 
acm_ntof=set_up_pet_model(ad_ntof,ct_phantom,pet_phantom)
acm_tof=set_up_pet_model(ad_tof,ct_phantom,pet_phantom)


start_time = time.time()
sino_ntof=acm_ntof.forward(pet_phantom)
ntoftime=(time.time() - start_time)

print("non tof done")

start_time = time.time()
sino_tof=acm_tof.forward(pet_phantom)
toftime= (time.time() - start_time)

print(ntoftime)
print(toftime)
```

**Comment by KrisThielemans** [comment]
So, I used [callgrind](https://www.valgrind.org/docs/manual/cl-manual.html). This doesn't strictly provide timing, but counts instruction and estimates cycles, but I guess it's good enough. I've ordered the results by cycles, but that doesn't really matter. This isn't hard to do: build `RelWithDebugInfo` (to get function info, otherwise you're lost) and run
```
valgrind --tool=callgrind forward_project whateverparameters
```
Below is what I get from forward projection with TOF

![image](https://user-images.githubusercontent.com/6362141/106070289-77a50900-6104-11eb-8d60-032dac802579.png)

I've selected the function that takes all the time (which is obviously [forward_project](https://github.com/NikEfth/STIR/blob/df86c03f00c06e3480cd3b9122daf212a3c9534a/src/recon_buildblock/ForwardProjectorByBinUsingProjMatrixByBin.cxx#L122)). For this run it took ~16K cycles, of which ~5.6K sit in `erff`, and ~1K in `Disc...::actual_get_relative_coordinates_for_indices`, as both of these are called ~50M times. Relevant lines are
https://github.com/NikEfth/STIR/blob/df86c03f00c06e3480cd3b9122daf212a3c9534a/src/include/stir/recon_buildblock/ProjMatrixByBin.inl#L200 and
https://github.com/NikEfth/STIR/blob/df86c03f00c06e3480cd3b9122daf212a3c9534a/src/include/stir/recon_buildblock/ProjMatrixByBin.inl#L171

This isn't too surprising (although the run-time for the `get_relative_coordinates...` is.  Its implementation is [here](https://github.com/NikEfth/STIR/blob/e0e40a90935b21b9cff3e51ff71ddd5dc30f8bf1/src/include/stir/DiscretisedDensityOnCartesianGrid.inl#L119)). It seems we could easily chop of 6/16 of the run-time by caching the TOF kernel, as opposed to recomputing it with `erf`), but that isn't enough..

**Comment by AnderBiguri** [comment]
Just as an extra info: `erf` tends to be slow, as we see. As an alternative to caching, `erf` tends to be approximated with a lookup table and linear interpolation in many applications. We lose some precision, of course, but in this case, are those 4th decimals that important? My hunch is that we can approximate it without any loss of general precision.

**Comment by AnderBiguri** [comment]
Francesca ran the same experiment as me, with ‘Discovery 710’, span=2, max_ring_diff=23 – with and without 11 TOF bins. 

My experiment above was on 32 cores, Francesca's on 4 cores. 
Result:
 ```
Ntoftime = 286
Toftime = 31018
```

For her, its 10 times slower than expected (110x the non-tof forward projector)

**Comment by KrisThielemans** [comment]
Thanks you give one result, but there should have been  2? Would be interesting to see hers vs yours. 

we know now why it's much slower. it's not just doing 29 times the non-TOF project (although in fact that's cached). it's the convolution that takes the time

**Comment by AnderBiguri** [comment]
Mine where:

```
12.0033020973  # no tof
1751.15560794  # 29 tof bins
```

**Comment by AnderBiguri** [comment]
I tested the following:

https://stackoverflow.com/questions/35148198/efficient-faithfully-rounded-implementation-of-error-function-erff

essentially, 1ULP max error erf() approximations. 

I get, with Niko's branch:
```
11.6452109814 #non tof
822.858706951 #tof 13 bins
```
with those erf() approximations
```
12.0176298618 #non tof
826.633433819 #tof 13 bins
```
i.e. basically no change. Likely C++ is implementing that SO post anyways.  

Wanted to give it a shot :)

**Comment by KrisThielemans** [comment]
While it is still slower than we'd like due to the current strategy of convolving the whole non-TOF `ProjMatrixElemsForOneBin`, the kernel changes and symmetries update is how far we currently plan to go.
